[parity]
chain = "configuration.json"
base_path = "./parity/io.parity.ethereum"
db_path = "./parity/io.parity.ethereum/chains"
keys_path = "./parity/io.parity.ethereum/keys"

[network]
reserved_peers = "./reserved-peers.txt"

[ui]
force = true

[rpc]
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[mining]
force_sealing = true
reseal_on_txs = "none"

[misc]
log_file = "parity.log"
