[parity]
chain = "configuration.json"
base_path = "./parity/io.parity.ethereum"
db_path = "./parity/io.parity.ethereum/chains"
keys_path = "./parity/io.parity.ethereum/keys"

[network]
bootnodes = ["enode://fdafb3a5cb9cd6db2bc0f53408ef1b6057786baacbfb85826f3ce610e6f03949ed6bf2b9965849cb13bc12bc5ddb6c224a232aae33084c2ba07b7fdf758f0752@192.241.235.242:30303"]

[ui]
force = true

[rpc]
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[mining]
force_sealing = true
reseal_on_txs = "none"
usd_per_tx = "0"

[misc]
log_file = "parity.log"
