[parity]
chain = "configuration.json"
base_path = "./parity/io.parity.ethereum"
db_path = "./parity/io.parity.ethereum/chains"
keys_path = "./parity/io.parity.ethereum/keys"

[network]
bootnodes = ["enode://3c38ed4a6823e205053a83ccfecd06afe7ff7ebcc0c123e800be41f5ba8d1de86351000471f5a7cd26f917248a49c2c21195a4a03e9f4576f1bbe99675e2d40b@192.241.235.242:30303"]

[ui]
force = true

[rpc]
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[mining]
force_sealing = true
reseal_on_txs = "none"
usd_per_tx = "0"

[misc]
log_file = "parity.log"
