[parity]
chain = "configuration.json"
base_path = "./parity/io.parity.ethereum"
db_path = "./parity/io.parity.ethereum/chains"
keys_path = "./parity/io.parity.ethereum/keys"

[mining]
force_sealing = true
reseal_on_txs = "all"
usd_per_tx = "0"

[misc]
log_file = "parity.log"
