[parity]
chain = "configuration.json"
base_path = "./parity/io.parity.ethereum"
db_path = "./parity/io.parity.ethereum/chains"
keys_path = "./parity/io.parity.ethereum/keys"

[ui]
disable = true

[rpc]
hosts = ["all"]
port = 8540
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore", "personal", "parity_accounts"]

[ipc]
disable = true

[websockets]
disable = true

[mining]
reseal_on_txs = "none"
usd_per_tx = "0"

[misc]
log_file = "parity.log"
